---
description: AFL Player Similarity
title: Player Similarity
runtime: shiny
---

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.16/iframeResizer.min.js"></script>
<style>
  iframe {
    min-width: 100%;
  }
</style>

**Player Similarity Index** is a measure of how similar two players statistical averages over the previous 10 games are, a value of 100 would indicate players are identical. To calculate the similarity index 16 different statistical categories are used, these include but are not limited to disposals, marks, contested vs uncontested, centre bounce attendances, intercepts, inside 50s, rebound 50s, etc.

This tool supports our [Defense vs Position](https://www.dfsaustralia.com/afl-dvp/){target="_blank"} tool and lets you delve deeper into how opposition concede points to certain types of players. For those season long players it's also a great option to help in selecting your captain choice.

If you like what we offer why not consider **SUPPORTING US** by buying a coffee?

<center>
<script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support Us', '#29abe0', 'E1E8C5INN');kofiwidget2.draw();</script> 
</center>

<iframe src="https://dfsaustralia-apps.com/shiny/afl/player-similarity/" width="100%" scrolling="no" frameborder="no"></iframe>

\

<script>
  iFrameResize({
    heightCalculationMethod: 'taggedElement'
  });
</script>
---

