---
description: AFL Player Lines
title: Player Lines
runtime: shiny
---

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.16/iframeResizer.min.js"></script>
<style>
  iframe {
    min-width: 100%;
  }
</style>

Theis application gives the user a quick and easy way of reviewing recent player performance (last 20 games) in key statistical categories, helping them make smarter decisions for Player Prop Bets. Games where players have played less than 50% TOG have been removed as to not skew the data. Note: only games from 2021 onwards are included

W% refers to the percentage of games that the given player has reached or exceeded the respective line over their last 20 games. These games are highlighted in green to help the user interpret the results more easily.

A projection is included (minimum of 10 games played is required) based on a weighted average giving a heavier weighting to more recent games. This projection gives no consideration to strength of matchup or weather conditions, the user should consider this if they wish to use the projections.

<center>
<script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('If You Have a WIN, Consider Buying Us a Coffee', '#29abe0', 'E1E8C5INN');kofiwidget2.draw();</script> 
</center>

---

<iframe src="https://dfsaustralia-apps.com/shiny/afl/player-lines/" width="100%" scrolling="no" frameborder="no"></iframe>

<script>
  iFrameResize({
    heightCalculationMethod: 'taggedElement'
  });
</script>
---

