---
title: "trial-iframe"
author: "Morts"
date: '2021-10-04'
output: html_document
categories: []
tags: []
slug: trial-iframe
runtime: shiny
---

# What is Value?

A popular way to try normalise player performance in the Fantasy Sports community is to define it in terms of a multiple of their salary. For example, if Tom Mitchell is priced at $15,000 and scores 105 fantasy points then he's deemed to have returned 7.00x his salary, e.g. (105 / 15,000) * 1000 = 7.00x. 

<iframe src="https://www.dfsaustralia-apps.com/shiny/draftstars-profit-tracker/" width="100%" height="700" frameborder="no"></iframe>

This common strategy gives coaches the ability to compare players across a range of salaries and make a decision on who they think is the best value play for their lineup. Value play? How many times have you been reading an article or scrolling Twitter and seen some version of "Player A returned value tonight" or "Player B is expected to hit value", etc? What is a players underlying value in terms of fantasy points?

In terms of multiples of a player's salary using one figure across all salaries is fraught with danger. For example, you'd be happy to take 105 (7.00x) from Tom Mitchell at $15,000 but you'd definitely want more than 35 (7.00x) fantasy points from a $5,000 player. Here in lies the conundrum, what is the underlying measure that defines value for an individual player?